// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSDecay

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;
float decayFactor;

[numthreads(8, 8, 1)]
void CSDecay(uint3 id : SV_DispatchThreadID)
{
    int2 coord = int2(id.x, id.y);
    float4 color = Result[coord];
    color.rgb *= decayFactor;
    Result[coord] = float4(color.rgb, 1); // keep alpha
}
